#!/bin/bash
#SBATCH -N 1
#SBATCH -c 1
#SBATCH --mem=4g
#SBATCH -t 120:00:00

# GWF generated code ...
cd /Users/mailund/Projects/SoftwareProjects/gwf/example
export GWF_JOBID=$SLURM_JOBID

# Script from workflow
bwa index -p ponAbe2 -a bwtsw ponAbe2.fa
