#!/bin/bash
#SBATCH -N 1
#SBATCH -c 16
#SBATCH --mem=4g
#SBATCH -t 120:00:00

# GWF generated code ...
cd /Users/mailund/Projects/SoftwareProjects/gwf/example
export GWF_JOBID=$SLURM_JOBID

# Script from workflow


bwa mem -t 16 ponAbe2 Masala_R1.fastq.gz Masala_R2.fastq.gz |     samtools view -Shb - > /scratch/$GWF_JOBID/unsorted.bam
samtools sort -o /scratch/$PBS_JOBID/unsorted.bam /scratch/$GWF_JOBID/sort |     samtools rmdup -s - Masala.unsorted.bam


