#!/Users/mailund/anaconda/bin/python

import os
import sys
from gwf.parser import parse


import argparse

parser = argparse.ArgumentParser(description='Show a workflow graph.')

parser.add_argument('-f', '--file', 
                    default='workflow.gwf', dest='workflow_file',
                    help='Workflow file if not the default (workflow.gwf).')

parser.add_argument('output', nargs='?', default='workflow.dot', 
					help='File to write the workflow graph to.')

args = parser.parse_args()

workflow = parse(args.workflow_file)


# FIXME: ERROR HANDLING
out = open(args.output, 'w')

workflow.dependency_graph.print_workflow_graph(out)
