#!/Users/mailund/anaconda/bin/python

# This is a simple script for testing if list transformations work as intended.
# It just prints all the lists in the workflow so the user can test that they are
# processed they way it was intended.

import os
import sys
from gwf.workflow_preprocessor import preprocess


import argparse

parser = argparse.ArgumentParser(description='Print workflow after text-preprocessing.')

parser.add_argument('-f', '--file', 
                    default='workflow.gwf', dest='workflow_file',
                    help='Workflow file if not the default (workflow.gwf).')

args = parser.parse_args()

workflow_text = preprocess(args.workflow_file)
print workflow_text