#!/Users/mailund/anaconda/bin/python

import argparse
import importlib


parser = argparse.ArgumentParser(description='Print targets with status.')

parser.add_argument('-f', '--file', 
                    default='workflow.py', dest='workflow_file',
                    help='Workflow file if not the default (workflow.py).')
parser.add_argument('-v', '--verbose', default=False, action='store_true',
                    help='Verbose output.')

args = parser.parse_args()



execfile(args.workflow_file)
from gwf_workflow.workflow import build_workflow
workflow = build_workflow()
nodes = workflow.targets

for name, node in nodes.items():
    print 'Target', name,
    if node.job_in_queue:
        print node.job_queue_status, '(ID: %s)' % node.jobID
    elif node.should_run:
        print 'should run'
    else:
        print 'is up to date'
