#!/Users/mailund/anaconda/bin/python

# This is a simple script for testing if list transformations work as intended.
# It just prints all the lists in the workflow so the user can test that they are
# processed they way it was intended.

import os
import sys
from gwf.parser import parse


import argparse

parser = argparse.ArgumentParser(description='Print processed lists.')

parser.add_argument('-f', '--file', 
                    default='workflow.gwf', dest='workflow_file',
                    help='Workflow file if not the default (workflow.gwf).')

args = parser.parse_args()

# FIXME: handle errors if the workflow fine is not found...
workflow = parse(args.workflow_file)
for lst in workflow.lists.values():
    print lst
