#!/Users/mailund/anaconda/bin/python

import os
import sys
from gwf.parser import parse
from gwf.graphviz import print_graphviz


import argparse

parser = argparse.ArgumentParser(description='Show a workflow graph.')

parser.add_argument('-f', '--file', 
                    default='workflow.gwf', dest='workflow_file',
                    help='Workflow file if not the default (workflow.gwf).')

parser.add_argument('output', nargs='?', default='workflow.dot', 
					help='File to write the workflow graph to.')

args = parser.parse_args()

workflow = parse(args.workflow_file)
out = open(args.output, 'w')
print_graphviz(workflow.dependency_graph, out)
