#!/Users/mailund/anaconda/bin/python

import os
import sys
from gwf.parser import parse
from gwf.graphviz import print_graphviz, print_graphviz_dependencies


import argparse

parser = argparse.ArgumentParser(description='''Print a workflow to the graphviz format for display.

If a target is provided, the dependency graph for that target is printed,
otherwise the entire workflow is printed.

''')

parser.add_argument('-f', '--file', 
                    default='workflow.gwf', dest='workflow_file',
                    help='Workflow file if not the default (workflow.gwf).')
parser.add_argument('-o', '--output', nargs='?', default='workflow.dot', 
					help='File to write the workflow graph to.')

parser.add_argument('target', nargs='?', default=None,
                    help='The target to print dependencies from.')

args = parser.parse_args()

if args.target is None:
	workflow = parse(args.workflow_file)
	out = open(args.output, 'w')
	print_graphviz(workflow.dependency_graph, out)
else:
	workflow = parse(args.workflow_file)
	graph = workflow.dependency_graph
	target = graph.nodes[args.target]
	out = open(args.output, 'w')
	print_graphviz_dependencies(graph, target, out)
