name: Run tests

on:
  pull_request:
    paths:
      - '.github/workflows/test.yml'
      - '**.py'
  push:
    paths:
      - '.github/workflows/test.yml'
      - '**.py'

jobs:
  test:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [macOS]
        python_version: ['3.6', '3.7', '3.8']

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-python@v1
      name: Install Python ${{ matrix.python_version }}
      with:
        python-version: ${{ matrix.python_version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install nox
      shell: bash

    - name: Run tests
      run: |
        python -m nox -s test-${{ matrix.python_version }}
      shell: bash

    - name: Submit coverage results
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: |
        pip install coveralls
        coveralls
