name: Run tests
on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 15
    strategy:
      fail-fast: true
      matrix:
        environment: ["py38", "py39", "py310", "py311", "py312", "py313"]

    steps:
      - uses: actions/checkout@v3
      - uses: prefix-dev/setup-pixi@v0.8.0
        with:
          pixi-version: v0.41.0
          environments: ${{ matrix.environment }}
          cache: true
      - run: pixi run --environment test-${{ matrix.environment }} test
